spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: 860204
  jpa:
    show-sql: true
  flyway:
    clean-disabled: false
    clean-on-validation-error: true